package io.helidon.examples.jaxrs.apt.runtime;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Marks classes generated by the JAX-RS annotation processor.
 */
@Retention(RetentionPolicy.SOURCE)
public @interface Generated {
    String value();
}
